name: Docker Image CI

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - name: Set environment variables,
      uses: sergeysova/jq-action@v2
      env:
        VARS: ${{ toJson(vars) }}
      with:
        run: echo "$VARS" | jq -r 'keys[] as $k | "echo \($k)=\(.[$k])"'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag express:${GITHUB_REF##*/}
