name: Docker Image CI

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3
    - name: Set environment variables
      run: echo PORT ${{ vars.PORT }} && echo PORT ${{ env.PORT }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag express:${GITHUB_REF##*/}
