name: Docker Image CI

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3
    - uses: sergeysova/jq-action@v2
    - name: Set environment variables,
      env:
        VARS: ${{ toJson(vars) }}
      run: echo "$VARS" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' > .env && cat .env
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag express:${{ github.ref_name }}
